apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-database-deployment
spec:
  selector: 
    matchLabels:
      app: recipe-database
  replicas: 1
  template:
    metadata:
      labels:
        app: recipe-database
    spec:
      containers:
      - name: database-container
        image: mariadb:loc.v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: lol123
