version: "3.3"
services:
  DB:
    build: .
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lol
      MYSQL_DATABASE: recipe
